name: Update Homebrew

on:
  workflow_run:
    workflows: ["Release naisdevice"]
    types:
      - completed
  workflow_dispatch:

jobs:
  update-cask:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Get Latest version
        id: latest_version
        uses: abatilo/release-info-action@5876e1e74bcf971982cc7bef9b65a8814621cf44
        with:
          owner: nais
          repo: device
      - name: Update version and checksum in cask
        id: update_cask
        env:
          LATEST: ${{ steps.latest_version.outputs.latest_tag }}
          LATEST_DATE: ${{ steps.latest_version.outputs.latest_tag_published_at }}
          HOMEBREW_TAP_KEY: ${{ secrets.HOMEBREW_TAP_KEY }}
        run: |
          echo "Version ${LATEST} was released at ${LATEST_DATE}"

          eval "$(ssh-agent -s)"
          ssh-add - <<< "${HOMEBREW_TAP_KEY}"
          git clone git@github.com:nais/homebrew-tap.git taprepo
          cd taprepo
          git config user.email "aura@nav.no"
          git config user.name "naisdevice pipeline"

          for pkg in naisdevice naisdevice-tenant ; do
            url=https://github.com/nais/device/releases/download/${LATEST}/${pkg}.pkg
            checksum=$(curl --location ${url}.sha256)
            sed -E -i "s#version \".*?\"#version \"${LATEST}\"#" Casks/${pkg}.rb
            sed -E -i "s#sha256 \".*?\"#sha256 \"${checksum}\"#" Casks/${pkg}.rb
          done

          git add Casks/naisdevice*.rb
          git --no-pager diff --cached
          git commit -a -m "Bump naisdevice.pkg version to ${LATEST}"
          git push
